import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/reactquery";
import { NextAuthProvider } from "@/providers/next-auth-provider";
import Header from "@/components/header";
import ReduxProvider from "@/providers/redux-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <ReduxProvider>
              <Header />
              {children}
            </ReduxProvider>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
